master:
    - name: mst_group
      collection: Group
      nature: Primary
      fields:
        - name: guid
          field: Guid
          type: text
        - name: name
          field: Name
          type: text
        - name: parent
          field: if $$IsEqual:$Parent:$$SysName:Primary then "" else $Parent
          type: text
        - name: primary_group
          field: _PrimaryGroup
          type: text
        - name: is_revenue
          field: IsRevenue
          type: logical
        - name: is_deemedpositive
          field: IsDeemedPositive
          type: logical
        - name: is_reserved
          field: IsReserved
          type: logical
        - name: affects_gross_profit
          field: AffectsGrossProfit
          type: logical
        - name: sort_position
          field: SortPosition
          type: number
    - name: mst_ledger
      collection: Ledger
      nature: Primary
      fields:
        - name: guid
          field: Guid
          type: text
        - name: name
          field: Name
          type: text
        - name: parent
          field: if $$IsEqual:$Parent:$$SysName:Primary then "" else $Parent
          type: text
        - name: alias
          field: OnlyAlias
          type: text
        - name: is_revenue
          field: IsRevenue
          type: logical
        - name: is_deemedpositive
          field: IsDeemedPositive
          type: logical
        - name: opening_balance
          field: OpeningBalance
          type: amount
        - name: description
          field: Description
          type: text
        - name: mailing_name
          field: MailingName
          type: text
        - name: mailing_address
          field: if $$IsEmpty:$Address then "" else $$FullList:Address:$Address
          type: text
        - name: mailing_state
          field: LedStateName
          type: text
        - name: mailing_country
          field: CountryName
          type: text
        - name: mailing_pincode
          field: PinCode
          type: text
        - name: email
          field: Email
          type: text
        - name: it_pan
          field: IncomeTaxNumber
          type: text
        - name: gstn
          field: Partygstin
          type: text
        - name: gst_registration_type
          field: Gstregistrationtype
          type: text
        - name: gst_supply_type
          field: Gsttypeofsupply
          type: text
        - name: gst_duty_head
          field: Gstdutyhead
          type: text
        - name: tax_rate
          field: RateOfTaxCalculation
          type: number
        - name: bank_account_holder
          field: Bankaccholdername
          type: text
        - name: bank_account_number
          field: BankDetails
          type: text
        - name: bank_ifsc
          field: Ifscode
          type: text
        - name: bank_swift
          field: Swiftcode
          type: text
        - name: bank_name
          field: Bankingconfigbank
          type: text
        - name: bank_branch
          field: BankBranchname
          type: text
    - name: mst_vouchertype
      collection: VoucherType
      nature: Primary
      fields:
        - name: guid
          field: Guid
          type: text
        - name: name
          field: Name
          type: text
        - name: parent
          field: Parent
          type: text
        - name: numbering_method
          field: NumberingMethod
          type: text
        - name: is_deemedpositive
          field: IsDeemedPositive
          type: logical
        - name: affects_stock
          field: AffectsStock
          type: logical
    - name: mst_uom
      collection: Unit
      nature: Primary
      fields:
        - name: guid
          field: Guid
          type: text
        - name: name
          field: Symbol
          type: text
        - name: formalname
          field: FormalName
          type: text
        - name: is_simple_unit
          field: IsSimpleUnit
          type: logical
        - name: base_units
          field: BaseUnits
          type: text
        - name: additional_units
          field: AdditionalUnits
          type: text
        - name: conversion
          field: Conversion
          type: number
    - name: mst_godown
      collection: Godown
      nature: Primary
      fields:
        - name: guid
          field: Guid
          type: text
        - name: name
          field: Name
          type: text
        - name: parent
          field: Parent
          type: text
        - name: address
          field: if $$IsEmpty:$Address then "" else $$FullList:Address:$Address
          type: text
    - name: mst_stock_group
      collection: StockGroup
      nature: Primary
      fields:
        - name: guid
          field: Guid
          type: text
        - name: name
          field: Name
          type: text
        - name: parent
          field: if $$IsEqual:$Parent:$$SysName:Primary then "" else $Parent
          type: text
    - name: mst_stock_item
      collection: StockItem
      nature: Primary
      fetch:
        - GstDetails,PartNo
      fields:
        - name: guid
          field: Guid
          type: text
        - name: name
          field: Name
          type: text
        - name: parent
          field: if $$IsEqual:$Parent:$$SysName:Primary then "" else $Parent
          type: text
        - name: alias
          field: OnlyAlias
          type: text
        - name: part_number
          field: PartNo
          type: text
        - name: uom
          field: if $$IsEqual:$BaseUnits:$$SysName:NotApplicable then "" else $BaseUnits
          type: text
        - name: alternate_uom
          field: if $$IsEqual:$AdditionalUnits:$$SysName:NotApplicable then "" else $AdditionalUnits
          type: text
        - name: conversion
          field: Conversion
          type: number
        - name: opening_balance
          field: $$StringFindAndReplace:($$Number:$$String:$OpeningBalance):"(-)":"-"
          type: number
        - name: opening_rate
          field: OpeningRate
          type: rate
        - name: opening_value
          field: OpeningValue
          type: amount
        - name: gst_type_of_supply
          field: GSTMSTTypeofSupply
          type: text
        - name: gst_hsn_code
          field: InfGSTHSNCode
          type: text
        - name: gst_hsn_description
          field: InfGSTHSNDescription
          type: text
        - name: gst_rate
          field: InfGSTIGSTRate
          type: text
        - name: gst_taxability
          field: InfGSTTaxablility
          type: text
    - name: mst_cost_category
      collection: CostCategory
      nature: Primary
      fields:
        - name: guid
          field: Guid
          type: text
        - name: name
          field: Name
          type: text
        - name: allocate_revenue
          field: AllocateRevenue
          type: logical
        - name: allocate_non_revenue
          field: AllocateNonRevenue
          type: logical
    - name: mst_cost_centre
      collection: CostCentre
      nature: Primary
      fields:
        - name: guid
          field: Guid
          type: text
        - name: name
          field: Name
          type: text
        - name: parent
          field: if $$IsEqual:$Parent:$$SysName:Primary then "" else $Parent
          type: text
        - name: category
          field: Category
          type: text
    - name: mst_gst_effective_rate
      collection: StockItem.GstDetails
      nature: Derived
      filters:
        - NOT $$IsEmpty:$GstApplicable
      fields:
        - name: item
          field: Name
          type: text
        - name: applicable_from
          field: Applicablefrom
          type: date
        - name: hsn_description
          field: Hsn
          type: text
        - name: hsn_code
          field: HsnCode
          type: text
        - name: rate
          field: if NOT $$IsEmpty:$StateWiseDetails then $StateWiseDetails[First].RateDetails[3].GstRate else 0
          type: number
        - name: is_rcm_applicable
          field: IsReverseChargeApplicable
          type: logical
        - name: nature_of_transaction
          field: GstNatureOfTransaction
          type: text
        - name: nature_of_goods
          field: NatureOfGoods
          type: text
        - name: supply_type
          field: SupplyType
          type: text
        - name: taxability
          field: Taxability
          type: text
    - name: mst_opening_batch_allocation
      collection: StockItem.BatchAllocations
      nature: Derived
      fields:
        - name: item
          field: ..Name
          type: text
        - name: opening_balance
          field: $$StringFindAndReplace:($$Number:$$String:$OpeningBalance):"(-)":"-"
          type: amount
        - name: opening_rate
          field: OpeningRate
          type: rate
        - name: opening_value
          field: OpeningValue
          type: amount
        - name: godown
          field: GodownName
          type: text
        - name: manufactured_on
          field: MfdOn
          type: date
    - name: mst_opening_bill_allocation
      collection: Ledger.BillAllocations
      nature: Derived
      fields:
        - name: ledger
          field: ..Name
          type: text
        - name: opening_balance
          field: OpeningBalance
          type: amount
        - name: bill_date
          field: BillDate
          type: date
        - name: name
          field: Name
          type: text
    - name: trn_closingstock_ledger
      collection: Ledger.LedgerClosingValues
      nature: Derived
      fetch:
        - LedgerClosingValues
      filters:
        - $$IsLedOfGrp:$Name:$$GroupStock
      fields:
        - name: ledger
          field: Name
          type: text
        - name: stock_date
          field: Date
          type: date
        - name: stock_value
          field: Amount
          type: amount
    - name: mst_stockitem_standard_cost
      collection: StockItem.StandardCostList
      nature: Derived
      fetch:
        - StandardCostList
      fields:
        - name: item
          field: Name
          type: text
        - name: date
          field: Date
          type: date
        - name: rate
          field: Rate
          type: rate
    - name: mst_stockitem_standard_price
      collection: StockItem.StandardPriceList
      nature: Derived
      fetch:
        - StandardPriceList
      fields:
        - name: item
          field: Name
          type: text
        - name: date
          field: Date
          type: date
        - name: rate
          field: Rate
          type: rate
transaction:
    - name: trn_voucher
      collection: Voucher
      nature: Primary
      fetch:
        - Narration,PartyLedgerName,PlaceOfSupply,Reference,ReferenceDate
      filters:
        - NOT $IsCancelled
        - NOT $IsOptional
      fields:
        - name: guid
          field: Guid
          type: text
        - name: date
          field: Date
          type: date
        - name: voucher_type
          field: VoucherTypeName
          type: text
        - name: voucher_number
          field: VoucherNumber
          type: text
        - name: reference_number
          field: Reference
          type: text
        - name: reference_date
          field: ReferenceDate
          type: date
        - name: narration
          field: Narration
          type: text
        - name: party_name
          field: PartyLedgerName
          type: text
        - name: place_of_supply
          field: PlaceOfSupply
          type: text
        - name: is_invoice
          field: IsInvoice
          type: logical
        - name: is_accounting_voucher
          field: if $$IsAccountingVch:$VoucherTypeName then 1 else 0
          type: logical
        - name: is_inventory_voucher
          field: if $$IsInventoryVch:$VoucherTypeName then 1 else 0
          type: logical
        - name: is_order_voucher
          field: if $$IsOrderVch:$VoucherTypeName then 1 else 0
          type: logical
    - name: trn_accounting
      collection: Voucher.AllLedgerEntries
      nature: Derived
      fetch:
        - AllLedgerEntries
      filters:
        - NOT $IsCancelled
        - NOT $IsOptional
      fields:
        - name: guid
          field: Guid
          type: text
        - name: ledger
          field: LedgerName
          type: text
        - name: amount
          field: Amount
          type: amount
        - name: amount_forex
          field: if $$IsEmpty:$$ForexValue:$Amount then 0 else $$StringFindAndReplace:(if $$IsDebit:$Amount then -$$ForexValue:$Amount else $$ForexValue:$Amount):"(-)":"-"
          type: amount
        - name: currency
          field: $$Currency:$Amount
          type: text
    - name: trn_inventory
      collection: Voucher.AllInventoryEntries
      nature: Derived
      fetch:
        - AllInventoryEntries
      filters:
        - NOT $IsCancelled
        - NOT $IsOptional
      fields:
        - name: guid
          field: Guid
          type: text
        - name: item
          field: StockItemName
          type: text
        - name: quantity
          field: ActualQty
          type: quantity
        - name: rate
          field: Rate
          type: rate
        - name: amount
          field: Amount
          type: amount
        - name: additional_amount
          field: AddlAmount
          type: amount
        - name: discount_amount
          field: Discount
          type: number
        - name: godown
          field: GodownName
          type: text
        - name: tracking_number
          field: if ($$IsEmpty:$TrackingNumber or $$IsNotApplicable:$TrackingNumber) then "" else $TrackingNumber
          type: text
        - name: order_number
          field: if ($$IsEmpty:$OrderNo or $$IsNotApplicable:$OrderNo) then "" else $OrderNo
          type: text
        - name: order_duedate
          field: OrderDueDate
          type: date
    - name: trn_cost_centre
      collection: Voucher.AllLedgerEntries.CostCentreAllocations
      nature: Derived
      fetch:
        - AllLedgerEntries
      filters:
        - NOT $IsCancelled
        - NOT $IsOptional
      fields:
        - name: guid
          field: Guid
          type: text
        - name: ledger
          field: LedgerName
          type: text
        - name: costcentre
          field: Name
          type: text
        - name: amount
          field: Amount
          type: amount
    - name: trn_bill
      collection: Voucher.AllLedgerEntries.BillAllocations
      nature: Derived
      fetch:
        - AllLedgerEntries
      filters:
        - NOT $IsCancelled
        - NOT $IsOptional
      fields:
        - name: guid
          field: Guid
          type: text
        - name: ledger
          field: LedgerName
          type: text
        - name: name
          field: Name
          type: text
        - name: amount
          field: Amount
          type: amount
        - name: billtype
          field: BillType
          type: text
    - name: trn_bank
      collection: Voucher.AllLedgerEntries.BankAllocations
      nature: Derived
      fetch:
        - AllLedgerEntries
      filters:
        - NOT $IsCancelled
        - NOT $IsOptional
      fields:
        - name: guid
          field: Guid
          type: text
        - name: ledger
          field: ..LedgerName
          type: text
        - name: transaction_type
          field: TransactionType
          type: text
        - name: instrument_date
          field: InstrumentDate
          type: date
        - name: instrument_number
          field: InstrumentNumber
          type: text
        - name: bank_name
          field: BankName
          type: text
        - name: amount
          field: Amount
          type: amount
    - name: trn_batch
      collection: Voucher.AllInventoryEntries.BatchAllocations
      nature: Derived
      fetch:
        - AllInventoryEntries
      filters:
        - NOT $IsCancelled
        - NOT $IsOptional
      fields:
        - name: guid
          field: Guid
          type: text
        - name: item
          field: StockItemName
          type: text
        - name: name
          field: BatchName
          type: text
        - name: quantity
          field: ActualQty
          type: quantity
        - name: amount
          field: Amount
          type: amount
        - name: godown
          field: GodownName
          type: text
        - name: destination_godown
          field: DestinationGodownName
          type: text
        - name: tracking_number
          field: if ($$IsEmpty:$TrackingNumber or $$IsNotApplicable:$TrackingNumber) then "" else $TrackingNumber
          type: text
